config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'posts#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true,
                        length: {minimum: 5}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title = 'About Us'
        @body = 'This is a rails backend project created by Mostafa ElDahshan'
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index #defining index as a controller to be refered to (root)
        @post = Post.all
    end

    def new #defining new as as resource in routes file
        @post = Post.new
    end

    def show #displaying post by id
        @post = Post.find(params[:id])
    end

    def create #Method for saving in DB using Model(Post)
        @post = Post.new(post_params) #assiging new post to Post Model to be saved in DB

        if(@post.save)
            redirect_to @post
        else
            render "new"
        end
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update #update method for updating post by id
        @post = Post.find(params[:id])
        if(@post.update(post_params))
            redirect_to @post
        else
            render "edit"
        end
    end

    def destroy #delete method taking post id and redirecting all posts page
        @post = Post.find(params[:id])
        @post.destroy

        redirect_to posts_path
    end

    private def post_params #defining what post consists of to save to db
        params.require(:post).permit(:title, :body) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"%>
  </head>

  <body>
      <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
      <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
        <h1 class="display-4 fw-bold lh-1">Blog Project</h1>
        <p class="lead">Created With Ruby on Rails By Mostafa ElDahshan</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
          <button type="button" class="btn btn-primary btn-lg px-4 me-md-2 fw-bold">
            <%= link_to "Home", home_path%>
          </button>
          <button type="button" class="btn btn-outline-secondary btn-lg px-4">
            <%= link_to "About", about_path%>
          </button>
          <button type="button" class="btn btn-outline-secondary btn-lg px-4">
            <%= link_to "New Post", new_post_path%>
          </button>
        </div>
      </div>
    </div>

<div class="container">
    <%= yield %>
</div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%=@title%></h1>
<p><%=@body%></p>

app/views/posts/edit.html.erb
<br>
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f|%>

    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p>
        <%= f.label :title%> <br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.label :body%> <br>
        <%= f.text_field(:body, {:class => 'form-control'})%>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>

app/views/posts/index.html.erb
<br>
<h1>All Blog Posts</h1>
<br>
<% @post.each do |post|%>
    <div class="well">
        <h3><%= post.title%></h3>
        <p><%= post.body%></p>
        <%=link_to "Read More", post_path(post), :class => 'btn btn-primary'%>
        <hr>
    </div>
<% end %>

app/views/posts/new.html.erb
<br>
<h1>Add Post</h1>
<%= form_for :post, url: posts_path do |f|%>

    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
        <% end %>
    <% end %>
    <p>
        <%= f.label :title%> <br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.label :body%> <br>
        <%= f.text_field(:body, {:class => 'form-control'})%>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>

<%= link_to "Edit Post", edit_post_path(@post), :class => 'btn btn-primary' %>

<%= link_to "Delete Post", post_path(@post), data: {method: :delete, confirm: 'Are you sure?'}, :class => 'btn btn-danger'%>
                            